"""AIGenerator — generate a Python AI wrapper from a COBOLAnalysis."""
from __future__ import annotations

from .analyzer import COBOLAnalysis

_WRAPPER_TEMPLATE = '''"""
Auto-generated Python AI wrapper for COBOL program: {program_id}
Source: {source_file}
Generated by antcrew COBOLAugment
"""
from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

# --------------------------------------------------------------------------
# Data model (mirrors COBOL {program_id} interface)
# --------------------------------------------------------------------------

{data_class}

# --------------------------------------------------------------------------
# AI integration layer
# --------------------------------------------------------------------------


class {class_name}AI:
    """{requirement}

    Wraps the COBOL program ``{program_id}`` with a Python interface and
    adds AI-driven logic.  The actual COBOL execution path depends on your
    runtime setup (batch job, REST adapter, MQ trigger, etc.).
    """

    def __init__(self, cobol_runner: str = "cobrun", program_path: str | None = None) -> None:
        self.cobol_runner = cobol_runner
        self.program_path = program_path or "{program_id}.cbl"

    # ------------------------------------------------------------------
    # Core method — AI-enhanced entry point
    # ------------------------------------------------------------------

    def process(self, input_data: dict[str, Any]) -> dict[str, Any]:
        """Process input through the AI layer before/after calling COBOL.

        Override this method to add your AI logic.
        """
        # Pre-processing: AI enrichment before COBOL
        enriched = self._ai_enrich(input_data)

        # Call COBOL program
        cobol_result = self._call_cobol(enriched)

        # Post-processing: AI interpretation of COBOL output
        return self._ai_interpret(cobol_result)

    def _ai_enrich(self, data: dict[str, Any]) -> dict[str, Any]:
        """Override to add AI-driven field enrichment before COBOL runs."""
        return data

    def _ai_interpret(self, result: dict[str, Any]) -> dict[str, Any]:
        """Override to add AI-driven interpretation of COBOL output."""
        return result

    # ------------------------------------------------------------------
    # COBOL bridge — adapt to your runtime
    # ------------------------------------------------------------------

    def _call_cobol(self, input_data: dict[str, Any]) -> dict[str, Any]:
        """Stub: replace with your actual COBOL invocation mechanism.

        Options:
        - Batch job via JCL (AS/400 SBMJOB / CALL command)
        - REST adapter wrapping the COBOL program
        - IBM MQ trigger
        - Direct compile + run (dev/test only)
        """
        # Example: write input to a temp file, call COBOL, read output
        raise NotImplementedError(
            "Implement _call_cobol() with your actual COBOL runtime bridge. "
            "See deployment_guide for options."
        )

    # ------------------------------------------------------------------
    # Serialisation helpers
    # ------------------------------------------------------------------

    @staticmethod
    def to_cobol_record(data: dict[str, Any]) -> str:
        """Serialize dict to a fixed-format COBOL record string."""
        return json.dumps(data)  # replace with fixed-format marshalling

    @staticmethod
    def from_cobol_record(record: str) -> dict[str, Any]:
        """Deserialize COBOL output record to dict."""
        return json.loads(record)  # replace with fixed-format unmarshalling
'''

_DATACLASS_TEMPLATE = '''from dataclasses import dataclass, field

@dataclass
class {class_name}Input:
    """Input fields for {program_id} ({section} section)."""
{fields}

@dataclass
class {class_name}Output:
    """Expected output from {program_id}."""
    return_code: int = 0
    message: str = ""
    data: dict = field(default_factory=dict)
'''


class AIGenerator:
    """Generate a Python AI wrapper from a :class:`~.analyzer.COBOLAnalysis`.

    When an *llm* is provided, the wrapper is produced by calling the LLM with
    a structured prompt.  Otherwise a static template is used.
    """

    def __init__(self, llm: object | None = None) -> None:
        self._llm = llm

    def generate(self, analysis: COBOLAnalysis, requirement: str) -> str:
        if self._llm is not None:
            return self._generate_with_llm(analysis, requirement)
        return self._generate_static(analysis, requirement)

    # ------------------------------------------------------------------
    # Static generator (no LLM)
    # ------------------------------------------------------------------

    def _generate_static(self, analysis: COBOLAnalysis, requirement: str) -> str:
        class_name = _safe_classname(analysis.program_id)

        fields_lines = []
        for item in (analysis.linkage_fields or analysis.working_storage_fields)[:20]:
            py_type = _cobol_pic_to_python(item.pic)
            fields_lines.append(f"    {_safe_name(item.name)}: {py_type} = {_default(py_type)}")

        if not fields_lines:
            fields_lines = ["    pass"]

        data_class = _DATACLASS_TEMPLATE.format(
            class_name=class_name,
            program_id=analysis.program_id,
            section="LINKAGE" if analysis.linkage_fields else "WORKING-STORAGE",
            fields="\n".join(fields_lines),
        )

        return _WRAPPER_TEMPLATE.format(
            program_id=analysis.program_id,
            source_file=analysis.source_file,
            class_name=class_name,
            requirement=requirement,
            data_class=data_class,
        )

    # ------------------------------------------------------------------
    # LLM generator
    # ------------------------------------------------------------------

    def _generate_with_llm(self, analysis: COBOLAnalysis, requirement: str) -> str:
        prompt = f"""You are a senior software engineer specializing in COBOL modernization.

Generate a Python class that acts as an AI-enhanced wrapper for the following COBOL program.

## COBOL Program Analysis
{analysis.summary()}

## New AI Requirement
{requirement}

## Instructions
1. Create a Python class `{_safe_classname(analysis.program_id)}AI` with a `process(input_data)` method.
2. Map the COBOL data items to Python dataclasses.
3. Add AI enrichment hooks before and after the COBOL call.
4. Include a `_call_cobol()` stub with clear comments on integration options.
5. Use type hints and docstrings.
6. Output ONLY the Python code, no markdown fences.
"""
        try:
            result = self._llm.invoke(prompt)  # type: ignore[union-attr]
            if hasattr(result, "content"):
                return result.content
            return str(result)
        except Exception:
            return self._generate_static(analysis, requirement)


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _safe_classname(name: str) -> str:
    return "".join(p.capitalize() for p in name.replace("-", "_").split("_"))


def _safe_name(name: str) -> str:
    return name.lower().replace("-", "_")


def _cobol_pic_to_python(pic: str) -> str:
    pic = pic.upper()
    if not pic:
        return "str"
    if "V" in pic or "." in pic:
        return "float"
    if pic.startswith("9") or pic.startswith("S9"):
        return "int"
    return "str"


def _default(py_type: str) -> str:
    if py_type == "int":
        return "0"
    if py_type == "float":
        return "0.0"
    return '""'
