"""Integrator — generate COBOL batch caller + deployment guide."""
from __future__ import annotations

from .analyzer import COBOLAnalysis

_COBOL_CALLER_TEMPLATE = """      *> Auto-generated COBOL bridge caller for AI integration
      *> Program: {program_id}
      *> Generated by antcrew COBOLAugment

       IDENTIFICATION DIVISION.
       PROGRAM-ID. {bridge_id}.

       ENVIRONMENT DIVISION.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  WS-RETURN-CODE          PIC S9(4) COMP-4.
       01  WS-HTTP-STATUS          PIC 9(3)  VALUE ZEROS.
       01  WS-REQUEST-DATA         PIC X(32000).
       01  WS-RESPONSE-DATA        PIC X(32000).

       LINKAGE SECTION.
{linkage_section}

       PROCEDURE DIVISION USING {using_fields}.
       MAIN-PARA.
           * Send data to Python AI service (REST adapter pattern)
           MOVE SPACES TO WS-REQUEST-DATA
           * Populate WS-REQUEST-DATA with input fields (JSON serialisation)
           CALL 'ANTCREW-SEND' USING WS-REQUEST-DATA
                                     WS-RESPONSE-DATA
                                     WS-HTTP-STATUS
           IF WS-HTTP-STATUS NOT = 200
               MOVE 1 TO WS-RETURN-CODE
               STOP RUN
           END-IF
           * Parse WS-RESPONSE-DATA and move back to output fields
           MOVE ZEROS TO WS-RETURN-CODE
           STOP RUN.
"""

_GUIDE_TEMPLATE = """# Deployment Guide: {program_id} + AI Integration

## Overview

This guide explains how to integrate the generated Python AI wrapper
(`{class_name}AI`) with the existing COBOL program `{program_id}`.

## Architecture

```
COBOL {program_id}
    |
    v  (CALL or JCL SBMJOB)
{bridge_id} (COBOL bridge caller)
    |
    v  (HTTP / MQ / shared memory)
{class_name}AI  (Python AI wrapper)
    |
    v
Your LLM / ML Model
```

## Integration Options

### Option A — REST Adapter (Recommended for AS/400)
1. Deploy `{class_name}AI` as a FastAPI service on a Linux/Windows server.
2. Expose `POST /process` that receives JSON and returns JSON.
3. Call `ANTCREW-SEND` subprogram from COBOL bridge (see generated `{bridge_id}.cbl`).
4. `ANTCREW-SEND` uses IBM HTTP Client (QTMHHTP1 on AS/400) or a C HTTP stub.

### Option B — IBM MQ Trigger
1. COBOL program writes to MQ queue instead of calling HTTP.
2. Python service listens on the queue via `ibm-mq` Python package.
3. Low latency, reliable, no synchronous coupling.

### Option C — Batch File Exchange
1. COBOL writes input to a flat file; Python reads and processes it.
2. Python writes output; COBOL reads on next cycle.
3. Suitable for overnight batch jobs with no real-time requirement.

## Prerequisites

- Python 3.11+
- `pip install antcrew[legacy]`
- IBM iSeries Access ODBC driver (for AS400Connector)
- Network access from AS/400 to Python service host (for Option A/B)

## Quick Start

```python
from antcrew.augment.cobol import COBOLAugment

aug = COBOLAugment(llm=your_llm)
result = aug.augment("{source_file}", requirement="Your requirement here")

# Save the wrapper
with open("{class_name_lower}_ai.py", "w") as f:
    f.write(result.python_wrapper)

# Save the COBOL caller
with open("{bridge_id}.cbl", "w") as f:
    f.write(result.cobol_caller)
```

## Data Items (WORKING-STORAGE)
{ws_fields}

## External Dependencies (COPY/CALL)
{external_calls}

## Testing

1. Unit test the Python wrapper with mocked COBOL responses.
2. Integration test with a COBOL stub that returns expected data.
3. Regression test: run the original COBOL program and the new AI wrapper
   in parallel; compare outputs for a sample of real transactions.

## Security

- Never pass unsanitised user input to the COBOL record layout.
- Validate JSON field lengths against COBOL PIC clause sizes.
- Use TLS for all HTTP communication between COBOL and Python hosts.
- Rotate service credentials at least every 90 days.
"""


class Integrator:
    """Generate COBOL-side integration artefacts."""

    def generate_caller(self, analysis: COBOLAnalysis) -> str:
        """Return a COBOL batch caller that bridges to the Python AI wrapper."""
        bridge_id = (analysis.program_id[:6] + "AI").upper()

        linkage_lines: list[str] = []
        using_fields: list[str] = []

        fields = analysis.linkage_fields or analysis.working_storage_fields[:10]
        for item in fields:
            pic = item.pic or "X(100)"
            linkage_lines.append(f"       01  LK-{item.name:<28} PIC {pic}.")
            using_fields.append(f"LK-{item.name}")

        if not linkage_lines:
            linkage_lines = ["       01  LK-INPUT-DATA               PIC X(4000)."]
            using_fields = ["LK-INPUT-DATA"]

        return _COBOL_CALLER_TEMPLATE.format(
            program_id=analysis.program_id,
            bridge_id=bridge_id,
            linkage_section="\n".join(linkage_lines),
            using_fields=" ".join(using_fields),
        )

    def generate_guide(self, analysis: COBOLAnalysis, python_wrapper: str) -> str:
        """Return a markdown deployment guide for the augmented program."""
        from .ai_generator import _safe_classname

        class_name = _safe_classname(analysis.program_id)
        bridge_id = (analysis.program_id[:6] + "AI").upper()

        ws_lines = [f"- `{f.name}` ({f.pic})" for f in analysis.working_storage_fields[:15]]
        ws_section = "\n".join(ws_lines) if ws_lines else "_No working-storage fields detected._"

        call_lines = [f"- {c.kind} `{c.target}`" for c in analysis.external_calls[:10]]
        ext_section = "\n".join(call_lines) if call_lines else "_None detected._"

        return _GUIDE_TEMPLATE.format(
            program_id=analysis.program_id,
            class_name=class_name,
            class_name_lower=class_name.lower(),
            bridge_id=bridge_id,
            source_file=analysis.source_file,
            ws_fields=ws_section,
            external_calls=ext_section,
        )
