"""
SetupAgent — generates an agentteam.yaml through an interactive CLI wizard.

Usage:
    antcrew setup                        # interactive wizard
    antcrew setup --output ./myproject/  # write to specific directory
    antcrew setup --name auth-service    # skip the name question
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Optional


# ── YAML template ────────────────────────────────────────────────────────────

_YAML_TEMPLATE = """\
# Generated by `antcrew setup`
# Run with: antcrew run "{request}" --config {filename}
# Docs: https://github.com/iagop99/antcrew

name: {name}
team: {team}

model:
  provider: {provider}
{model_line}
{project_block}\
{cache_block}\
{runner_block}\
"""

_MODEL_LINES = {
    "claude":    "  model: claude-sonnet-4-6",
    "gpt4":      "  model: gpt-4o",
    "gemini":    "  model: gemini-1.5-flash",
    "ollama":    "  model: llama3\n  base_url: http://localhost:11434",
    "simulated": "",
}

_TEAM_MAP = {
    "software":   "dev",
    "fullstack":  "fullstack",
    "research":   "research",
    "content":    "content",
}

_MODEL_KEY_HINTS = {
    "claude":    "  → Requires ANTHROPIC_API_KEY",
    "gpt4":      "  → Requires OPENAI_API_KEY",
    "gemini":    "  → Requires GOOGLE_API_KEY",
    "ollama":    "  → Requires Ollama running locally (ollama serve)",
    "simulated": "  → No API key needed — useful for testing",
}


def _slugify(name: str) -> str:
    name = name.lower().strip()
    name = re.sub(r"[^\w\s-]", "", name)
    return re.sub(r"[\s_]+", "-", name)


# ── SetupAgent class ──────────────────────────────────────────────────────────

class SetupAgent:
    """
    Conversational setup wizard that generates an antcrew.yaml.

    Can be used programmatically or through `antcrew setup` CLI.
    """

    def __init__(self) -> None:
        self._answers: dict = {}

    def run_wizard(
        self,
        *,
        name: Optional[str] = None,
        output_dir: Path = Path("."),
        filename: str = "agentteam.yaml",
    ) -> Path:
        """
        Run the interactive wizard and write the generated YAML.

        Returns the path to the written file.
        """
        from rich.console import Console
        from rich.prompt import Prompt, Confirm
        from rich.panel import Panel

        console = Console()
        console.print()
        console.print(Panel.fit(
            "[bold green]antcrew setup[/bold green] — configuración interactiva\n"
            "[dim]Presiona Enter para aceptar el valor por defecto[/dim]",
            border_style="green",
        ))
        console.print()

        # 1. Project name
        if name:
            project_name = _slugify(name)
        else:
            raw = Prompt.ask("[bold]¿Cómo se llama tu proyecto?[/bold]", default="mi-proyecto")
            project_name = _slugify(raw)

        # 2. What to build (free text, informational)
        description = Prompt.ask(
            "[bold]¿Qué quieres construir?[/bold] [dim](descripción breve)[/dim]",
            default="",
        )

        # 3. Project type
        console.print("\n[bold]¿Qué tipo de proyecto?[/bold]")
        console.print("  [cyan]1[/cyan] Software (API / backend / web app)")
        console.print("  [cyan]2[/cyan] Full-stack (frontend + backend)")
        console.print("  [cyan]3[/cyan] Investigación (análisis, informes)")
        console.print("  [cyan]4[/cyan] Contenido (blog, marketing, documentación)")
        type_choice = Prompt.ask("Elige", choices=["1", "2", "3", "4"], default="1") or "1"
        team = ["software", "fullstack", "research", "content"][int(type_choice) - 1]
        team_key = _TEAM_MAP[team]

        # 4. AI model
        console.print("\n[bold]¿Qué modelo de IA?[/bold]")
        for i, (key, hint) in enumerate(_MODEL_KEY_HINTS.items(), 1):
            console.print(f"  [cyan]{i}[/cyan] {key.capitalize()}{hint}")
        model_choice = Prompt.ask("Elige", choices=["1", "2", "3", "4", "5"], default="1") or "1"
        provider = list(_MODEL_KEY_HINTS.keys())[int(model_choice) - 1]

        # 5. Persistent sessions
        use_project = Confirm.ask(
            "\n¿Guardar sesiones persistentes entre runs?", default=True
        )

        # 6. LLM cache
        use_cache = Confirm.ask("¿Activar caché de LLM? (ahorra coste en runs repetidos)", default=True)

        # 7. Test runner
        console.print("\n[bold]¿Sandbox para ejecutar tests?[/bold]")
        console.print("  [cyan]1[/cyan] Ninguno")
        console.print("  [cyan]2[/cyan] Local  (pytest / npm test)")
        console.print("  [cyan]3[/cyan] Docker (aislado)")
        runner_choice = Prompt.ask("Elige", choices=["1", "2", "3"], default="1") or "1"
        runner_type = ["none", "local", "docker"][int(runner_choice) - 1]

        # ── Build YAML ──────────────────────────────────────────────────────

        model_line = _MODEL_LINES.get(provider, "")

        project_block = ""
        if use_project:
            project_block = f"project: {project_name}.json\n"

        cache_block = ""
        if use_cache:
            cache_block = "cache: ~/.antcrew/cache.db\n"

        runner_block = ""
        if runner_type == "local":
            runner_block = "\nrunner:\n  type: local\n  test_cmd: pytest\n"
        elif runner_type == "docker":
            runner_block = "\nrunner:\n  type: docker\n  image: python:3.12-slim\n  test_cmd: pytest\n"

        yaml_content = _YAML_TEMPLATE.format(
            name=project_name,
            team=team_key,
            provider=provider,
            model_line=model_line,
            project_block=project_block,
            cache_block=cache_block,
            runner_block=runner_block,
            request=description or "Describe tu tarea aquí",
            filename=filename,
        )

        # Write file
        output_dir.mkdir(parents=True, exist_ok=True)
        dest = output_dir / filename
        dest.write_text(yaml_content, encoding="utf-8")

        # Summary
        console.print()
        console.print(Panel(
            f"[bold green]✅ {dest}[/bold green]\n\n"
            f"[dim]Para usarlo:[/dim]\n"
            f"  antcrew run \"{description or 'Tu tarea'}\" --config {dest}\n\n"
            f"[dim]O con sesión persistente:[/dim]\n"
            f"  antcrew project run --config {dest}",
            title="Configuración generada",
            border_style="green",
        ))
        console.print()

        return dest
