"""Multi-LLM cost routing — automatic model selection per agent.

Policies
--------
none     No automatic routing; models come from workspace.agent_models and run-level
         model_overrides (existing behaviour, unchanged).

economy  Every agent is routed to the platform's cheap tier model regardless of its
         role.  Explicit run-level overrides still win.

auto     Each agent is classified by its class name against keyword patterns and
         routed to the appropriate tier (cheap / standard / premium).  Explicit
         workspace agent_models entries and run-level overrides still win.

Precedence (highest → lowest)
------------------------------
1. Run-level model_overrides (explicit, per-call)
2. Workspace agent_models named entries (explicit, per-workspace)
3. Cost router overrides (this module — economy or auto)
4. Workspace agent_models "default" key
5. Platform PlatformConfig.default_agent_models["default"]
6. Hardcoded "claude"
"""
from __future__ import annotations

from typing import Optional

# ---------------------------------------------------------------------------
# Tier classification maps
# ---------------------------------------------------------------------------

# Team-level classification — checked first (more specific)
_TEAM_TIERS: dict[str, str] = {
    # cheap: simple I/O, formatting, routing
    "webhooksink": "cheap",
    "webhook": "cheap",

    # standard: most development and content work
    "devteam": "standard",
    "fullstack": "standard",
    "content": "standard",
    "feature": "standard",
    "research": "standard",
    "codemigration": "standard",

    # premium: legal, security, architecture review
    "legal": "premium",
    "security": "premium",
    "audit": "premium",
}

# Agent-level classification — keyword matching (case-insensitive)
_AGENT_TIERS: list[tuple[str, str]] = [
    # cheap — simple, deterministic tasks
    ("validator",    "cheap"),
    ("formatter",    "cheap"),
    ("extractor",    "cheap"),
    ("summarizer",   "cheap"),
    ("summary",      "cheap"),
    ("router",       "cheap"),
    ("sink",         "cheap"),
    ("monitor",      "cheap"),

    # premium — complex reasoning
    ("architect",    "premium"),
    ("planner",      "premium"),
    ("legal",        "premium"),
    ("compliance",   "premium"),
    ("security",     "premium"),
    ("auditor",      "premium"),

    # standard — everything else (coding, review, research)
    ("developer",    "standard"),
    ("dev",          "standard"),
    ("coder",        "standard"),
    ("reviewer",     "standard"),
    ("researcher",   "standard"),
    ("writer",       "standard"),
    ("tester",       "standard"),
    ("engineer",     "standard"),
]

_VALID_POLICIES = frozenset({"none", "economy", "auto"})


def classify_team(team_name: str) -> str:
    """Return cheap|standard|premium for a team name. Falls back to 'standard'."""
    key = team_name.lower()
    for pattern, tier in _TEAM_TIERS.items():
        if pattern in key:
            return tier
    return "standard"


def classify_agent(agent_name: str) -> str:
    """Return cheap|standard|premium for an agent class name. Falls back to 'standard'."""
    key = agent_name.lower()
    for pattern, tier in _AGENT_TIERS:
        if pattern in key:
            return tier
    return "standard"


def build_routing_overrides(
    team_name: str,
    policy: str,
    tiers: dict[str, str],
    *,
    known_agents: Optional[list[str]] = None,
) -> dict[str, str]:
    """Return a model-overrides dict generated by the routing policy.

    The result is used as the LOWEST-priority layer — workspace explicit entries
    and run-level overrides always override it.

    Args:
        team_name:    team being dispatched (e.g. "DevTeam")
        policy:       "none" | "economy" | "auto"
        tiers:        {"cheap": model, "standard": model, "premium": model}
        known_agents: optional list of agent class names in the team

    Returns:
        dict like {"default": "groq:...", "ArchitectAgent": "claude:..."} or {}
    """
    if policy == "none" or not tiers:
        return {}

    cheap = tiers.get("cheap", "")
    standard = tiers.get("standard", "")
    premium = tiers.get("premium", "")

    if policy == "economy":
        return {"default": cheap} if cheap else {}

    if policy == "auto":
        overrides: dict[str, str] = {}
        team_tier = classify_team(team_name)
        overrides["default"] = tiers.get(team_tier, standard) or standard
        if known_agents:
            for agent in known_agents:
                agent_tier = classify_agent(agent)
                model = tiers.get(agent_tier, standard) or standard
                if model and model != overrides.get("default"):
                    overrides[agent] = model
        return overrides

    return {}
