"""Sync AntCrew tickets to third-party PM systems (GitHub Issues, Linear, Jira)."""
from __future__ import annotations

import logging
from typing import Optional

log = logging.getLogger(__name__)


async def _sync_to_github(ticket: dict, cfg: dict) -> Optional[dict]:
    """POST a ticket as a GitHub Issue. cfg: {token, owner, repo}."""
    import httpx

    token = cfg.get("token", "")
    owner = cfg.get("owner", "")
    repo = cfg.get("repo", "")
    if not all([token, owner, repo]):
        log.warning("ticket_sync: github destination missing token/owner/repo")
        return None

    body_parts = [ticket.get("description", "")]
    ac = ticket.get("acceptance_criteria", "")
    if ac:
        body_parts.append(f"\n**Acceptance criteria**\n{ac}")
    priority = ticket.get("priority", "medium")
    body_parts.append(f"\n---\n*Priority: {priority} · Generated by [antcrew](https://antcrew.org)*")

    try:
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.post(
                f"https://api.github.com/repos/{owner}/{repo}/issues",
                headers={
                    "Authorization": f"Bearer {token}",
                    "Accept": "application/vnd.github+json",
                    "X-GitHub-Api-Version": "2022-11-28",
                },
                json={"title": ticket.get("title", "(untitled)"), "body": "\n".join(body_parts)},
            )
        if r.status_code == 201:
            data = r.json()
            return {"url": data.get("html_url"), "id": data.get("number")}
        log.warning("ticket_sync: github returned %d — %s", r.status_code, r.text[:200])
    except Exception as exc:
        log.warning("ticket_sync: github request failed: %s", exc)
    return None


async def _sync_to_linear(ticket: dict, cfg: dict) -> Optional[dict]:
    """Create a Linear issue via GraphQL. cfg: {api_key, team_id}."""
    import httpx

    api_key = cfg.get("api_key", "")
    team_id = cfg.get("team_id", "")
    if not all([api_key, team_id]):
        log.warning("ticket_sync: linear destination missing api_key/team_id")
        return None

    desc_parts = [ticket.get("description", "")]
    ac = ticket.get("acceptance_criteria", "")
    if ac:
        desc_parts.append(f"\n**Acceptance criteria**\n{ac}")

    priority_map = {"critical": 1, "high": 2, "medium": 3, "low": 4}
    priority_num = priority_map.get(ticket.get("priority", "medium"), 3)

    query = """
    mutation CreateIssue($title: String!, $description: String, $teamId: String!, $priority: Int) {
      issueCreate(input: {
        title: $title, description: $description, teamId: $teamId, priority: $priority
      }) {
        success
        issue { id url identifier }
      }
    }
    """
    try:
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.post(
                "https://api.linear.app/graphql",
                headers={"Authorization": api_key, "Content-Type": "application/json"},
                json={
                    "query": query,
                    "variables": {
                        "title": ticket.get("title", "(untitled)"),
                        "description": "\n".join(desc_parts),
                        "teamId": team_id,
                        "priority": priority_num,
                    },
                },
            )
        data = r.json()
        issue = data.get("data", {}).get("issueCreate", {}).get("issue") or {}
        if issue.get("url"):
            return {"url": issue["url"], "id": issue.get("identifier")}
        log.warning("ticket_sync: linear response had no issue: %s", str(data)[:300])
    except Exception as exc:
        log.warning("ticket_sync: linear request failed: %s", exc)
    return None


async def _sync_to_jira(ticket: dict, cfg: dict) -> Optional[dict]:
    """Create a Jira issue. cfg: {base_url, email, api_token, project_key}."""
    import base64

    import httpx

    base_url = cfg.get("base_url", "").rstrip("/")
    email = cfg.get("email", "")
    api_token = cfg.get("api_token", "")
    project_key = cfg.get("project_key", "")
    if not all([base_url, email, api_token, project_key]):
        log.warning("ticket_sync: jira destination missing required config fields")
        return None

    creds = base64.b64encode(f"{email}:{api_token}".encode()).decode()

    desc_text = ticket.get("description", "")
    ac = ticket.get("acceptance_criteria", "")
    if ac:
        desc_text = f"{desc_text}\n\nAcceptance criteria: {ac}"

    try:
        async with httpx.AsyncClient(timeout=15) as client:
            r = await client.post(
                f"{base_url}/rest/api/3/issue",
                headers={
                    "Authorization": f"Basic {creds}",
                    "Accept": "application/json",
                    "Content-Type": "application/json",
                },
                json={
                    "fields": {
                        "project": {"key": project_key},
                        "summary": ticket.get("title", "(untitled)"),
                        "issuetype": {"name": "Task"},
                        "description": {
                            "type": "doc",
                            "version": 1,
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [{"type": "text", "text": desc_text}],
                                }
                            ],
                        },
                    }
                },
            )
        if r.status_code in (200, 201):
            data = r.json()
            issue_key = data.get("key", "")
            return {"url": f"{base_url}/browse/{issue_key}", "id": issue_key}
        log.warning("ticket_sync: jira returned %d — %s", r.status_code, r.text[:200])
    except Exception as exc:
        log.warning("ticket_sync: jira request failed: %s", exc)
    return None


_PROVIDER_ADAPTERS: dict = {
    "github": _sync_to_github,
    "linear": _sync_to_linear,
    "jira": _sync_to_jira,
}


async def sync_tickets_to_destinations(
    run_id: str,
    tickets: list[dict],
    workspace_id: int,
    team_name: str,
) -> None:
    """Send all non-manual-action tickets to every enabled PM destination for the workspace+team."""
    if not tickets or not workspace_id:
        return
    try:
        from sqlmodel import select
        from sqlmodel.ext.asyncio.session import AsyncSession

        from app.core.database import engine as _db_engine
        from app.models.integrations import TicketDestination

        async with AsyncSession(_db_engine, expire_on_commit=False) as sess:
            dests = (await sess.exec(
                select(TicketDestination)
                .where(TicketDestination.workspace_id == workspace_id)
                .where(TicketDestination.enabled == True)  # noqa: E712
            )).all()
    except Exception as exc:
        log.warning("ticket_sync: failed to load destinations for workspace %d: %s", workspace_id, exc)
        return

    for dest in dests:
        if dest.team_filter and dest.team_filter != team_name:
            continue
        adapter = _PROVIDER_ADAPTERS.get(dest.provider)
        if not adapter:
            continue
        for ticket in tickets:
            if ticket.get("ticket_type") == "manual_action":
                continue
            try:
                result = await adapter(ticket, dest.config_json or {})
                if result:
                    log.info(
                        "ticket_sync: run=%s ticket=%s → %s %s",
                        run_id,
                        ticket.get("ticket_id", "?"),
                        dest.provider,
                        result.get("url", ""),
                    )
            except Exception as exc:
                log.warning(
                    "ticket_sync: run=%s dest=%d (%s) failed: %s",
                    run_id, dest.id, dest.provider, exc,
                )
