"""antcrew.engine — re-exports from antcrew_engine.engine (backward compatibility).

The canonical implementation lives in the ``antcrew-engine`` package
(``antcrew_engine.engine``).  This shim ensures that existing code which
imports from ``antcrew.engine`` continues to work without modification.
"""
from antcrew_engine.engine import (
    Artifact,
    ArtifactDelta,
    ArtifactId,
    ArtifactKind,
    EMPTY_DELTA,
    ArtifactStore,
    MemoryStore,
    FilesystemStore,
    MultiRepoStore,
    Condition,
    ConditionId,
    Constraints,
    DesiredProjectState,
    Goal,
    ProjectState,
    CapabilityDescriptor,
    CapabilityResult,
    Executor,
    Validator,
    ValidatorResult,
    CapabilityRegistry,
    Event,
    EventLog,
    EngineStarted,
    EngineFinished,
    EngineError,
    StateObserved,
    CapabilityDispatched,
    CapabilityCompleted,
    ConditionSatisfied,
    ConditionInvalidated,
    OperatorDecision,
    Operator,
    OperatorError,
    CapabilitySelector,
    CheapestFirst,
    FirstMatch,
    MostProductive,
    PrioritySelector,
    EventBusBridge,
)

__all__ = [
    "Artifact", "ArtifactId", "ArtifactKind", "ArtifactDelta", "EMPTY_DELTA",
    "ArtifactStore", "MemoryStore", "FilesystemStore", "MultiRepoStore",
    "Condition", "ConditionId", "DesiredProjectState", "Constraints", "Goal",
    "ProjectState",
    "CapabilityDescriptor", "CapabilityResult", "Executor",
    "Validator", "ValidatorResult",
    "CapabilityRegistry",
    "Event", "EventLog",
    "EngineStarted", "EngineFinished", "EngineError",
    "StateObserved", "CapabilityDispatched", "CapabilityCompleted",
    "ConditionSatisfied", "ConditionInvalidated", "OperatorDecision",
    "Operator", "OperatorError",
    "CapabilitySelector", "CheapestFirst", "FirstMatch", "MostProductive", "PrioritySelector",
    "EventBusBridge",
]
