"""antcrew — Public API.

All exports are lazy: submodules are only imported on first attribute access, so
``import antcrew`` does not materialise the full dependency tree.  CLI cold-start
drops from ~1.8 s to ~0.6 s.  Attribute caching (``globals()[name] = value``) means
every subsequent access is a plain dict lookup — no overhead after the first call.
"""
from __future__ import annotations

import importlib
from typing import Any

# ---------------------------------------------------------------------------
# Optional-dependency map — ImportError → None (same behaviour as before)
# ---------------------------------------------------------------------------
_OPTIONAL_MAP: dict[str, tuple[str, str]] = {
    "OpenAIModel":         ("antcrew.models.openai_model",                "OpenAIModel"),
    "AzureOpenAIModel":    ("antcrew.models.azure_openai_model",           "AzureOpenAIModel"),
    "LiteLLMModel":        ("antcrew.models.litellm_model",                "LiteLLMModel"),
    "TelegramChannel":     ("antcrew.integrations.telegram.integration",   "TelegramChannel"),
    "TelegramIntegration": ("antcrew.integrations.telegram.integration",   "TelegramIntegration"),
    "AgentBotConfig":      ("antcrew.integrations.telegram.integration",   "AgentBotConfig"),
}

# ---------------------------------------------------------------------------
# Lazy import map — name → (module_path, attribute_in_module)
# Attribute may differ from name (e.g. SandboxRunResult ← sandbox.RunResult)
# ---------------------------------------------------------------------------
_LAZY_MAP: dict[str, tuple[str, str]] = {
    # Agents
    "APIDesignAgent":      ("antcrew.agents.api_design",        "APIDesignAgent"),
    "CloudArchitectAgent": ("antcrew.agents.cloud_architect",   "CloudArchitectAgent"),
    "CodebaseScannerAgent":("antcrew.agents.codebase_scanner",  "CodebaseScannerAgent"),
    "CoherenceAgent":      ("antcrew.agents.coherence",         "CoherenceAgent"),
    "ConflictAgent":       ("antcrew.agents.conflict",          "ConflictAgent"),
    "CostAgent":           ("antcrew.agents.cost",              "CostAgent"),
    "DataAnalystAgent":    ("antcrew.agents.data_analyst",      "DataAnalystAgent"),
    "DBSchemaAgent":       ("antcrew.agents.db_schema",         "DBSchemaAgent"),
    "DesignSystemAgent":   ("antcrew.agents.design_system",     "DesignSystemAgent"),
    "DevOpsAgent":         ("antcrew.agents.devops",            "DevOpsAgent"),
    "DirectAgent":         ("antcrew.agents.direct_agent",      "DirectAgent"),
    "DiscoveryAgent":      ("antcrew.agents.discovery",         "DiscoveryAgent"),
    "DocWriterAgent":      ("antcrew.agents.doc_writer",        "DocWriterAgent"),
    "EmailCampaignAgent":  ("antcrew.agents.email_campaign",    "EmailCampaignAgent"),
    "FeatureAgent":        ("antcrew.agents.feature_agent",     "FeatureAgent"),
    "FeatureTeam":         ("antcrew.agents.feature_agent",     "FeatureTeam"),
    "PMAgent":             ("antcrew.agents.pm",                "PMAgent"),
    "instantiate_agent":   ("antcrew.agents.registry",          "instantiate_agent"),
    "ResearcherAgent":     ("antcrew.agents.researcher",        "ResearcherAgent"),
    "RetroAgent":          ("antcrew.agents.retro",             "RetroAgent"),
    "ReviewerAgent":       ("antcrew.agents.reviewer",          "ReviewerAgent"),
    "SecurityAgent":       ("antcrew.agents.security",          "SecurityAgent"),
    "SEOAnalystAgent":     ("antcrew.agents.seo_analyst",       "SEOAnalystAgent"),
    "SocialMediaAgent":    ("antcrew.agents.social_media",      "SocialMediaAgent"),
    "SprintPlannerAgent":  ("antcrew.agents.sprint_planner",    "SprintPlannerAgent"),
    "TemplateAgent":       ("antcrew.agents.template_agent",    "TemplateAgent"),
    "load_template_agent": ("antcrew.agents.template_agent",    "load_template_agent"),
    "register_transform":  ("antcrew.agents.template_agent",    "register_transform"),
    # Artifacts
    "ARTIFACT_REGISTRY":   ("antcrew.core.artifacts", "ARTIFACT_REGISTRY"),
    "PRD":                 ("antcrew.core.artifacts", "PRD"),
    "ArtifactContract":    ("antcrew.core.artifacts", "ArtifactContract"),
    "ArtifactHistory":     ("antcrew.core.artifacts", "ArtifactHistory"),
    "ArtifactVersion":     ("antcrew.core.artifacts", "ArtifactVersion"),
    "CloudArchSpec":       ("antcrew.core.artifacts", "CloudArchSpec"),
    "CloudService":        ("antcrew.core.artifacts", "CloudService"),
    "CodeArtifact":        ("antcrew.core.artifacts", "CodeArtifact"),
    "CodebaseAnalysis":    ("antcrew.core.artifacts", "CodebaseAnalysis"),
    "CodeReview":          ("antcrew.core.artifacts", "CodeReview"),
    "ConflictItem":        ("antcrew.core.artifacts", "ConflictItem"),
    "ConflictReport":      ("antcrew.core.artifacts", "ConflictReport"),
    "ContentPiece":        ("antcrew.core.artifacts", "ContentPiece"),
    "ContractError":       ("antcrew.core.artifacts", "ContractError"),
    "DataAnalysisReport":  ("antcrew.core.artifacts", "DataAnalysisReport"),
    "DatabaseSchema":      ("antcrew.core.artifacts", "DatabaseSchema"),
    "DataInsight":         ("antcrew.core.artifacts", "DataInsight"),
    "DBColumn":            ("antcrew.core.artifacts", "DBColumn"),
    "DBTable":             ("antcrew.core.artifacts", "DBTable"),
    "DesignSystemComponent":("antcrew.core.artifacts","DesignSystemComponent"),
    "DesignSystemDoc":     ("antcrew.core.artifacts", "DesignSystemDoc"),
    "DesignTokens":        ("antcrew.core.artifacts", "DesignTokens"),
    "DevOpsArtifact":      ("antcrew.core.artifacts", "DevOpsArtifact"),
    "DiscoveryContext":    ("antcrew.core.artifacts", "DiscoveryContext"),
    "DiscoveryQA":         ("antcrew.core.artifacts", "DiscoveryQA"),
    "DocumentationArtifact":("antcrew.core.artifacts","DocumentationArtifact"),
    "EmailCampaign":       ("antcrew.core.artifacts", "EmailCampaign"),
    "ResearchDocument":    ("antcrew.core.artifacts", "ResearchDocument"),
    "RetroReport":         ("antcrew.core.artifacts", "RetroReport"),
    "Screen":              ("antcrew.core.artifacts", "Screen"),
    "SecurityFinding":     ("antcrew.core.artifacts", "SecurityFinding"),
    "SecurityReport":      ("antcrew.core.artifacts", "SecurityReport"),
    "SEOAnalysis":         ("antcrew.core.artifacts", "SEOAnalysis"),
    "SocialMediaPlan":     ("antcrew.core.artifacts", "SocialMediaPlan"),
    "TestArtifact":        ("antcrew.core.artifacts", "TestArtifact"),
    "Ticket":              ("antcrew.core.artifacts", "Ticket"),
    "UIDesignSpec":        ("antcrew.core.artifacts", "UIDesignSpec"),
    "coerce_list":         ("antcrew.core.artifacts", "coerce_list"),
    "coerce_model":        ("antcrew.core.artifacts", "coerce_model"),
    "resolve_artifact_schema":("antcrew.core.artifacts","resolve_artifact_schema"),
    # Core
    "BaseChannel":         ("antcrew.core.channel",          "BaseChannel"),
    "FeedbackLoop":        ("antcrew.core.feedback",         "FeedbackLoop"),
    "FeedbackResult":      ("antcrew.core.feedback",         "FeedbackResult"),
    "FeedbackRunner":      ("antcrew.core.feedback",         "FeedbackRunner"),
    "Pipeline":            ("antcrew.core.pipeline",         "Pipeline"),
    "ProjectKB":           ("antcrew.core.project_kb",       "ProjectKB"),
    "LLMClassifier":       ("antcrew.core.router",           "LLMClassifier"),
    "RouteClassifier":     ("antcrew.core.router",           "RouteClassifier"),
    "Router":              ("antcrew.core.router",           "Router"),
    "RuleClassifier":      ("antcrew.core.router",           "RuleClassifier"),
    "FanOut":              ("antcrew.core.supervisor",       "FanOut"),
    "ParallelGroup":       ("antcrew.core.supervisor",       "ParallelGroup"),
    "Supervisor":          ("antcrew.core.supervisor",       "Supervisor"),
    "fan_out":             ("antcrew.core.supervisor",       "fan_out"),
    "parallel":            ("antcrew.core.supervisor",       "parallel"),
    "MinimalPipeline":     ("antcrew.core.task_classifier",  "MinimalPipeline"),
    "TaskType":            ("antcrew.core.task_classifier",  "TaskType"),
    "classify_task":       ("antcrew.core.task_classifier",  "classify_task"),
    "BaseTool":            ("antcrew.core.tools",            "BaseTool"),
    "CodeExecutorTool":    ("antcrew.core.tools",            "CodeExecutorTool"),
    "ListDirTool":         ("antcrew.core.tools",            "ListDirTool"),
    "ReadFileTool":        ("antcrew.core.tools",            "ReadFileTool"),
    "ToolResult":          ("antcrew.core.tools",            "ToolResult"),
    "WebSearchTool":       ("antcrew.core.tools",            "WebSearchTool"),
    "WriteFileTool":       ("antcrew.core.tools",            "WriteFileTool"),
    "Event":               ("antcrew.core.events",           "Event"),
    "EventBus":            ("antcrew.core.events",           "EventBus"),
    "bus":                 ("antcrew.core.events",           "bus"),
    "capture":             ("antcrew.core.events",           "capture"),
    "new_run_id":          ("antcrew.core.events",           "new_run_id"),
    "CostLimitExceeded":   ("antcrew.core.exceptions",       "CostLimitExceeded"),
    "AllGate":             ("antcrew.core.gates",            "AllGate"),
    "AnyGate":             ("antcrew.core.gates",            "AnyGate"),
    "BaseGate":            ("antcrew.core.gates",            "BaseGate"),
    "GateError":           ("antcrew.core.gates",            "GateError"),
    "GateResult":          ("antcrew.core.gates",            "GateResult"),
    "JsonGate":            ("antcrew.core.gates",            "JsonGate"),
    "NonEmptyGate":        ("antcrew.core.gates",            "NonEmptyGate"),
    "PythonSyntaxGate":    ("antcrew.core.gates",            "PythonSyntaxGate"),
    "SchemaGate":          ("antcrew.core.gates",            "SchemaGate"),
    "parse_gate":          ("antcrew.core.gates",            "parse_gate"),
    "GroupChat":           ("antcrew.core.group_chat",       "GroupChat"),
    "GroupChatResult":     ("antcrew.core.group_chat",       "GroupChatResult"),
    "FlexibleHITL":        ("antcrew.core.hitl",             "FlexibleHITL"),
    "HITLAction":          ("antcrew.core.hitl",             "HITLAction"),
    "HITLDecision":        ("antcrew.core.hitl",             "HITLDecision"),
    "RunResult":           ("antcrew.core.run_result",       "RunResult"),
    "Workflow":            ("antcrew.core.workflow_builder",  "Workflow"),
    "WorkflowBuilder":     ("antcrew.core.workflow_builder",  "WorkflowBuilder"),
    "compute_team_hash":   ("antcrew.core.agent",            "compute_team_hash"),
    "BaseOperator":        ("antcrew.core.operators",        "BaseOperator"),
    "CopyOp":              ("antcrew.core.operators",        "CopyOp"),
    "DropOp":              ("antcrew.core.operators",        "DropOp"),
    "MapOp":               ("antcrew.core.operators",        "MapOp"),
    "MergeOp":             ("antcrew.core.operators",        "MergeOp"),
    "RenameOp":            ("antcrew.core.operators",        "RenameOp"),
    "SetOp":               ("antcrew.core.operators",        "SetOp"),
    "build_operator":      ("antcrew.core.operators",        "build_operator"),
    "validate_agent_dag":  ("antcrew.core.validation",       "validate_agent_dag"),
    # Integrations
    "ConfluenceIntegration":("antcrew.integrations.confluence","ConfluenceIntegration"),
    "ConsoleChannel":      ("antcrew.integrations.console",  "ConsoleChannel"),
    "GitHubIntegration":   ("antcrew.integrations.github",   "GitHubIntegration"),
    "BigQueryTool":        ("antcrew.integrations.google_cloud","BigQueryTool"),
    "GCSTool":             ("antcrew.integrations.google_cloud","GCSTool"),
    "JiraIntegration":     ("antcrew.integrations.jira",     "JiraIntegration"),
    "SlackChannel":        ("antcrew.integrations.slack",    "SlackChannel"),
    # Models
    "ComparisonLLM":       ("antcrew.models.comparison",     "ComparisonLLM"),
    "FallbackLLM":         ("antcrew.models.fallback",       "FallbackLLM"),
    "GeminiModel":         ("antcrew.models.gemini_model",   "GeminiModel"),
    "SimulatedLLM":        ("antcrew.models.simulated",      "SimulatedLLM"),
    "FileLLMCache":        ("antcrew.models.cache",          "FileLLMCache"),
    "LLMCache":            ("antcrew.models.cache",          "LLMCache"),
    # Teams
    "AsyncContentTeam":    ("antcrew.teams.async_teams",     "AsyncContentTeam"),
    "AsyncCustomTeam":     ("antcrew.teams.async_teams",     "AsyncCustomTeam"),
    "AsyncDevTeam":        ("antcrew.teams.async_teams",     "AsyncDevTeam"),
    "AsyncFeatureTeam":    ("antcrew.teams.async_teams",     "AsyncFeatureTeam"),
    "AsyncFullStackTeam":  ("antcrew.teams.async_teams",     "AsyncFullStackTeam"),
    "AsyncResearchTeam":   ("antcrew.teams.async_teams",     "AsyncResearchTeam"),
    "AsyncRouter":         ("antcrew.teams.async_teams",     "AsyncRouter"),
    "ContentTeam":         ("antcrew.teams.content_team",    "ContentTeam"),
    "DevTeam":             ("antcrew.teams.dev_team",        "DevTeam"),
    "FullStackTeam":       ("antcrew.teams.fullstack_team",  "FullStackTeam"),
    "ResearchTeam":        ("antcrew.teams.research_team",   "ResearchTeam"),
    "AGENT_ARTIFACT":      ("antcrew.teams.base",            "AGENT_ARTIFACT"),
    "CustomTeam":          ("antcrew.teams.custom_team",     "CustomTeam"),
    # Misc packages
    "SqliteSaver":         ("antcrew.checkpointers",         "SqliteSaver"),
    "TeamContext":         ("antcrew.config",                "TeamContext"),
    "build_llm":           ("antcrew.config",                "build_llm"),
    "build_runner":        ("antcrew.config",                "build_runner"),
    "load_context":        ("antcrew.config",                "load_context"),
    "format_flow":         ("antcrew.flow",                  "format_flow"),
    "load_flow":           ("antcrew.flow",                  "load_flow"),
    "validate_flow":       ("antcrew.flow",                  "validate_flow"),
    "Project":             ("antcrew.project",               "Project"),
    "QuickStart":          ("antcrew.quickstart",            "QuickStart"),
    "DockerRunner":        ("antcrew.sandbox",               "DockerRunner"),
    "ExecutionResult":     ("antcrew.sandbox",               "ExecutionResult"),
    "LocalRunner":         ("antcrew.sandbox",               "LocalRunner"),
    "SandboxRunResult":    ("antcrew.sandbox",               "RunResult"),
    "SandboxRunner":       ("antcrew.sandbox",               "SandboxRunner"),
    "ReplayError":         ("antcrew.trace",                 "ReplayError"),
    "TraceLog":            ("antcrew.trace",                 "TraceLog"),
    # Capabilities
    "Architect":           ("antcrew.capabilities",          "Architect"),
    "BugFixer":            ("antcrew.capabilities",          "BugFixer"),
    "CodeGenerator":       ("antcrew.capabilities",          "CodeGenerator"),
    "CodeRegenerator":     ("antcrew.capabilities",          "CodeRegenerator"),
    "CodeReviewer":        ("antcrew.capabilities",          "CodeReviewer"),
    "DependencyInstaller": ("antcrew.capabilities",          "DependencyInstaller"),
    "DocGenerator":        ("antcrew.capabilities",          "DocGenerator"),
    "HitlReviewer":        ("antcrew.capabilities",          "HitlReviewer"),
    "ReviewFixer":         ("antcrew.capabilities",          "ReviewFixer"),
    "SpecExtractor":       ("antcrew.capabilities",          "SpecExtractor"),
    "TaskPlanner":         ("antcrew.capabilities",          "TaskPlanner"),
    "TeamExecutor":        ("antcrew.capabilities",          "TeamExecutor"),
    "TestGenerator":       ("antcrew.capabilities",          "TestGenerator"),
    "TestRunner":          ("antcrew.capabilities",          "TestRunner"),
    # Engine
    "EMPTY_DELTA":         ("antcrew.engine", "EMPTY_DELTA"),
    "Artifact":            ("antcrew.engine", "Artifact"),
    "ArtifactDelta":       ("antcrew.engine", "ArtifactDelta"),
    "ArtifactId":          ("antcrew.engine", "ArtifactId"),
    "ArtifactKind":        ("antcrew.engine", "ArtifactKind"),
    "ArtifactStore":       ("antcrew.engine", "ArtifactStore"),
    "CapabilityDescriptor":("antcrew.engine", "CapabilityDescriptor"),
    "CapabilityRegistry":  ("antcrew.engine", "CapabilityRegistry"),
    "CapabilityResult":    ("antcrew.engine", "CapabilityResult"),
    "CapabilitySelector":  ("antcrew.engine", "CapabilitySelector"),
    "CheapestFirst":       ("antcrew.engine", "CheapestFirst"),
    "Condition":           ("antcrew.engine", "Condition"),
    "ConditionId":         ("antcrew.engine", "ConditionId"),
    "Constraints":         ("antcrew.engine", "Constraints"),
    "DesiredProjectState": ("antcrew.engine", "DesiredProjectState"),
    "EngineLoop":          ("antcrew.engine", "EngineLoop"),
    "EngineLoopError":     ("antcrew.engine", "EngineLoopError"),
    "EventBusBridge":      ("antcrew.engine", "EventBusBridge"),
    "EventLog":            ("antcrew.engine", "EventLog"),
    "Executor":            ("antcrew.engine", "Executor"),
    "FilesystemStore":     ("antcrew.engine", "FilesystemStore"),
    "FirstMatch":          ("antcrew.engine", "FirstMatch"),
    "Goal":                ("antcrew.engine", "Goal"),
    "MemoryStore":         ("antcrew.engine", "MemoryStore"),
    "MostProductive":      ("antcrew.engine", "MostProductive"),
    "MultiRepoStore":      ("antcrew.engine", "MultiRepoStore"),
    "PrioritySelector":    ("antcrew.engine", "PrioritySelector"),
    "ProjectState":        ("antcrew.engine", "ProjectState"),
    "Validator":           ("antcrew.engine", "Validator"),
    "ValidatorResult":     ("antcrew.engine", "ValidatorResult"),
    # Eval
    "AgentImprovement":    ("antcrew.eval", "AgentImprovement"),
    "AgentScore":          ("antcrew.eval", "AgentScore"),
    "EvalCase":            ("antcrew.eval", "EvalCase"),
    "EvalFeedbackAgent":   ("antcrew.eval", "EvalFeedbackAgent"),
    "EvalReport":          ("antcrew.eval", "EvalReport"),
    "EvalRunner":          ("antcrew.eval", "EvalRunner"),
    "EvalSuite":           ("antcrew.eval", "EvalSuite"),
    "ImprovementPlan":     ("antcrew.eval", "ImprovementPlan"),
    "JudgeResult":         ("antcrew.eval", "JudgeResult"),
    # MCP
    "MCPRegistry":         ("antcrew.tools.mcp", "MCPRegistry"),
    "MCPTool":             ("antcrew.tools.mcp", "MCPTool"),
    "MCPToolset":          ("antcrew.tools.mcp", "MCPToolset"),
    # Memory
    "BaseMemory":          ("antcrew.memory.store",      "BaseMemory"),
    "ChromaMemory":        ("antcrew.memory.chroma",     "ChromaMemory"),
    "InMemoryMemory":      ("antcrew.memory.store",      "InMemoryMemory"),
    "MemoryResult":        ("antcrew.memory.store",      "MemoryResult"),
    "RunSnapshot":         ("antcrew.memory.store",      "RunSnapshot"),
    "RepoIndex":           ("antcrew.memory.repo_index", "RepoIndex"),
    # Presets
    "AgentPreset":         ("antcrew.presets", "AgentPreset"),
    "get_preset":          ("antcrew.presets", "get_preset"),
    "CONCISE":             ("antcrew.presets", "CONCISE"),
    "STRICT":              ("antcrew.presets", "STRICT"),
    "VERBOSE":             ("antcrew.presets", "VERBOSE"),
    "CAREFUL":             ("antcrew.presets", "CAREFUL"),
    # Testing
    "SequencedLLM":        ("antcrew.testing",           "SequencedLLM"),
    # Persistence
    "load_state":          ("antcrew.utils.persistence", "load_state"),
    "save_state":          ("antcrew.utils.persistence", "save_state"),
}


def __getattr__(name: str) -> Any:
    """Module-level lazy loader — imports submodules on first attribute access."""
    if name in _OPTIONAL_MAP:
        module_path, attr = _OPTIONAL_MAP[name]
        try:
            value = getattr(importlib.import_module(module_path), attr)
        except ImportError:
            value = None
        globals()[name] = value
        return value

    if name in _LAZY_MAP:
        module_path, attr = _LAZY_MAP[name]
        value = getattr(importlib.import_module(module_path), attr)
        globals()[name] = value
        return value

    raise AttributeError(f"module 'antcrew' has no attribute {name!r}")


# ---------------------------------------------------------------------------
# __version__ — resolved immediately (importlib.metadata is stdlib, cheap)
# ---------------------------------------------------------------------------
try:
    from importlib.metadata import version as _v
    __version__: str = _v("antcrew")
except Exception:
    __version__ = "unknown"


# ---------------------------------------------------------------------------
# __all__ — public API surface (unchanged from previous version)
# ---------------------------------------------------------------------------
__all__ = [
    # Teams
    "DevTeam",
    "FullStackTeam",
    "ResearchTeam",
    "ContentTeam",
    "CustomTeam",
    # Async teams
    "AsyncDevTeam",
    "AsyncFullStackTeam",
    "AsyncResearchTeam",
    "AsyncContentTeam",
    "AsyncCustomTeam",
    "AsyncFeatureTeam",
    "AsyncRouter",
    # Core
    "Supervisor",
    "ParallelGroup",
    "parallel",
    "FanOut",
    "fan_out",
    "Pipeline",
    # Tools
    "BaseTool",
    "ToolResult",
    "WebSearchTool",
    "CodeExecutorTool",
    "ReadFileTool",
    "WriteFileTool",
    "ListDirTool",
    "BaseChannel",
    "DevOpsArtifact",
    "DocumentationArtifact",
    # Agents (commonly used standalone)
    "APIDesignAgent",
    "CloudArchitectAgent",
    "CodebaseScannerAgent",
    "ConflictAgent",
    "CostAgent",
    "DataAnalystAgent",
    "DBSchemaAgent",
    "DesignSystemAgent",
    "DevOpsAgent",
    "DirectAgent",
    "DiscoveryAgent",
    "DocWriterAgent",
    "EmailCampaignAgent",
    "FeatureAgent",
    "FeatureTeam",
    "PMAgent",
    "ResearcherAgent",
    "RetroAgent",
    "ReviewerAgent",
    "SecurityAgent",
    "SEOAnalystAgent",
    "SocialMediaAgent",
    "SprintPlannerAgent",
    # Router
    "Router",
    "RouteClassifier",
    "LLMClassifier",
    "RuleClassifier",
    # Feedback loop
    "FeedbackRunner",
    "FeedbackLoop",
    "FeedbackResult",
    # Artifact contracts
    "PRD",
    "CodeArtifact",
    "TestArtifact",
    "CodeReview",
    "ResearchDocument",
    "ContentPiece",
    "CodebaseAnalysis",
    "Ticket",
    "UIDesignSpec",
    "Screen",
    "DesignTokens",
    "ConflictItem",
    "ConflictReport",
    "RetroReport",
    "SecurityFinding",
    "SecurityReport",
    "DiscoveryQA",
    "DiscoveryContext",
    "ArtifactContract",
    "CloudArchSpec",
    "CloudService",
    "ContractError",
    "DataAnalysisReport",
    "DataInsight",
    "DatabaseSchema",
    "DBColumn",
    "DBTable",
    "DesignSystemComponent",
    "DesignSystemDoc",
    "EmailCampaign",
    "SEOAnalysis",
    "SocialMediaPlan",
    "ARTIFACT_REGISTRY",
    "resolve_artifact_schema",
    "coerce_model",
    "coerce_list",
    # Models
    "SimulatedLLM",
    "GeminiModel",
    "OpenAIModel",
    "AzureOpenAIModel",
    "FallbackLLM",
    "ComparisonLLM",
    "LLMCache",
    "FileLLMCache",
    # Project & config
    "Project",
    "load_context",
    "TeamContext",
    "build_llm",
    "build_runner",
    # Sandbox
    "SandboxRunner",
    "LocalRunner",
    "DockerRunner",
    "ExecutionResult",
    "RunResult",
    "SandboxRunResult",
    "SqliteSaver",
    "CostLimitExceeded",
    # Gates
    "BaseGate",
    "GateResult",
    "GateError",
    "NonEmptyGate",
    "PythonSyntaxGate",
    "JsonGate",
    "SchemaGate",
    "AllGate",
    "AnyGate",
    "parse_gate",
    "TraceLog",
    "ReplayError",
    # Quick-start
    "QuickStart",
    # Workflow builder
    "WorkflowBuilder",
    "Workflow",
    # Group chat
    "GroupChat",
    "GroupChatResult",
    # HITL
    "FlexibleHITL",
    "HITLAction",
    "HITLDecision",
    # Artifact history
    "ArtifactHistory",
    "ArtifactVersion",
    # Google Cloud tools
    "BigQueryTool",
    "GCSTool",
    # Flow
    "load_flow",
    "validate_flow",
    "format_flow",
    # Channels
    "ConsoleChannel",
    "SlackChannel",
    "TelegramChannel",
    "TelegramIntegration",
    "AgentBotConfig",
    # External integrations
    "JiraIntegration",
    "GitHubIntegration",
    "ConfluenceIntegration",
    # Persistence
    "save_state",
    "load_state",
    # Memory
    "BaseMemory",
    "ChromaMemory",
    "InMemoryMemory",
    "MemoryResult",
    "RunSnapshot",
    "RepoIndex",
    # Eval
    "AgentImprovement",
    "AgentScore",
    "EvalCase",
    "EvalFeedbackAgent",
    "EvalReport",
    "EvalRunner",
    "EvalSuite",
    "ImprovementPlan",
    "JudgeResult",
    # Governance
    "compute_team_hash",
    # Models (optional)
    "LiteLLMModel",
    # MCP tools
    "MCPRegistry",
    "MCPTool",
    "MCPToolset",
    # Presets
    "AgentPreset",
    "get_preset",
    "CONCISE",
    "STRICT",
    "VERBOSE",
    "CAREFUL",
    # Template agents
    "TemplateAgent",
    "load_template_agent",
    "register_transform",
    # Registry
    "instantiate_agent",
    "AGENT_ARTIFACT",
    # Operators
    "BaseOperator",
    "RenameOp",
    "CopyOp",
    "DropOp",
    "SetOp",
    "MapOp",
    "MergeOp",
    "build_operator",
    # Validation
    "validate_agent_dag",
    # Testing
    "SequencedLLM",
    # Engine capabilities
    "Architect",
    "BugFixer",
    "CodeGenerator",
    "CodeRegenerator",
    "CodeReviewer",
    "DependencyInstaller",
    "DocGenerator",
    "HitlReviewer",
    "ReviewFixer",
    "SpecExtractor",
    "TaskPlanner",
    "TeamExecutor",
    "TestGenerator",
    "TestRunner",
    "Artifact",
    "ArtifactId",
    "ArtifactKind",
    "ArtifactDelta",
    "EMPTY_DELTA",
    "ArtifactStore",
    "MemoryStore",
    "FilesystemStore",
    "MultiRepoStore",
    "Condition",
    "ConditionId",
    "DesiredProjectState",
    "Constraints",
    "Goal",
    "ProjectState",
    "CapabilityDescriptor",
    "CapabilityResult",
    "Executor",
    "ValidatorResult",
    "Validator",
    "CapabilityRegistry",
    "EventLog",
    "EngineLoop",
    "EngineLoopError",
    "CapabilitySelector",
    "CheapestFirst",
    "FirstMatch",
    "MostProductive",
    "PrioritySelector",
    "EventBusBridge",
    # Events
    "bus",
    "Event",
    "EventBus",
    "capture",
    "new_run_id",
    # Advanced / task-level
    "CoherenceAgent",
    "ProjectKB",
    "TaskType",
    "classify_task",
    "MinimalPipeline",
]
